"""empty message

Revision ID: 9a4cf6b8a27b
Revises: d184426d0be8
Create Date: 2021-01-12 15:02:24.921594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a4cf6b8a27b'
down_revision = 'd184426d0be8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial', sa.Column('leasehold_improvements', sa.Numeric(), nullable=False))
    op.drop_column('financial', 'leashold_improvements')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial', sa.Column('leashold_improvements', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.drop_column('financial', 'leasehold_improvements')
    # ### end Alembic commands ###
