"""empty message

Revision ID: a9f67e4d75cc
Revises: 9a4cf6b8a27b
Create Date: 2021-01-12 15:04:20.378467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9f67e4d75cc'
down_revision = '9a4cf6b8a27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial', sa.Column('net_fixed_assets', sa.Numeric(), nullable=False))
    op.drop_column('financial', 'total_net_fixed_assets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('financial', sa.Column('total_net_fixed_assets', mysql.DECIMAL(precision=10, scale=0), nullable=False))
    op.drop_column('financial', 'net_fixed_assets')
    # ### end Alembic commands ###
