"""empty message

Revision ID: febd4b0a6266
Revises: 
Create Date: 2021-01-08 00:56:55.736677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'febd4b0a6266'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('first_name', sa.String(length=250), nullable=False),
    sa.Column('last_name', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prospect',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('industry', sa.String(length=250), nullable=False),
    sa.Column('address1', sa.String(length=250), nullable=False),
    sa.Column('city', sa.String(length=250), nullable=False),
    sa.Column('state', sa.String(length=250), nullable=False),
    sa.Column('zipCode', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=250), nullable=False),
    sa.Column('account', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=250), nullable=False),
    sa.Column('last_name', sa.String(length=250), nullable=False),
    sa.Column('position', sa.String(length=250), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('phone_number', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('first_name')
    )
    op.create_table('financial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('statement_date', sa.Integer(), nullable=True),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('fye_month', sa.Integer(), nullable=True),
    sa.Column('fye_day', sa.Integer(), nullable=True),
    sa.Column('prepared_by', sa.Integer(), nullable=True),
    sa.Column('cash', sa.Numeric(), nullable=False),
    sa.Column('accounts_receivable', sa.Numeric(), nullable=False),
    sa.Column('raw_materials', sa.Numeric(), nullable=False),
    sa.Column('work_in_process', sa.Numeric(), nullable=False),
    sa.Column('finished_goods', sa.Numeric(), nullable=False),
    sa.Column('total_inventory', sa.Numeric(), nullable=False),
    sa.Column('land', sa.Numeric(), nullable=False),
    sa.Column('construction_in_progress', sa.Numeric(), nullable=False),
    sa.Column('buildings', sa.Numeric(), nullable=False),
    sa.Column('machines_and_equipment', sa.Numeric(), nullable=False),
    sa.Column('furniture_and_fixtures', sa.Numeric(), nullable=False),
    sa.Column('vehicles', sa.Numeric(), nullable=False),
    sa.Column('leashold_improvements', sa.Numeric(), nullable=False),
    sa.Column('capital_leases', sa.Numeric(), nullable=False),
    sa.Column('other_fixed_assets', sa.Numeric(), nullable=False),
    sa.Column('total_gross_fixed_assets', sa.Numeric(), nullable=False),
    sa.Column('accumulated_depreciation', sa.Numeric(), nullable=False),
    sa.Column('total_net_fixed_assets', sa.Numeric(), nullable=False),
    sa.Column('other_operating_assets', sa.Numeric(), nullable=False),
    sa.Column('goodwill', sa.Numeric(), nullable=False),
    sa.Column('other_intangibles', sa.Numeric(), nullable=False),
    sa.Column('total_intangibles', sa.Numeric(), nullable=False),
    sa.Column('accumulated_amortization', sa.Numeric(), nullable=False),
    sa.Column('net_intangibles', sa.Numeric(), nullable=False),
    sa.Column('other_non_operating_assets', sa.Numeric(), nullable=False),
    sa.Column('total_non_current_assets', sa.Numeric(), nullable=False),
    sa.Column('total_assets', sa.Numeric(), nullable=False),
    sa.Column('short_term_debt_secured', sa.Numeric(), nullable=False),
    sa.Column('short_term_debt_unsecured', sa.Numeric(), nullable=False),
    sa.Column('cpltd_secured', sa.Numeric(), nullable=False),
    sa.Column('cpltd_unsecured', sa.Numeric(), nullable=False),
    sa.Column('other_notes_payable', sa.Numeric(), nullable=False),
    sa.Column('accounts_payable_trade', sa.Numeric(), nullable=False),
    sa.Column('other_current_liabilities', sa.Numeric(), nullable=False),
    sa.Column('total_current_liabilities', sa.Numeric(), nullable=False),
    sa.Column('ltd_secured', sa.Numeric(), nullable=False),
    sa.Column('ltd_unsecured', sa.Numeric(), nullable=False),
    sa.Column('other_lt_notes_payable', sa.Numeric(), nullable=False),
    sa.Column('other_operating_liaibilities', sa.Numeric(), nullable=False),
    sa.Column('other_non_operating_liabilities', sa.Numeric(), nullable=False),
    sa.Column('total_non_current_liabilities', sa.Numeric(), nullable=False),
    sa.Column('total_liabilities', sa.Numeric(), nullable=False),
    sa.Column('common_stock', sa.Numeric(), nullable=False),
    sa.Column('additional_paid_in_capital', sa.Numeric(), nullable=False),
    sa.Column('retained_earnings', sa.Numeric(), nullable=False),
    sa.Column('total_equity', sa.Numeric(), nullable=False),
    sa.Column('tangible_net_worth', sa.Numeric(), nullable=False),
    sa.Column('working_capital', sa.Numeric(), nullable=False),
    sa.Column('current_ratio', sa.Numeric(), nullable=False),
    sa.Column('quick_ratio', sa.Numeric(), nullable=False),
    sa.Column('leverage', sa.Numeric(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(), nullable=False),
    sa.Column('total_cogs', sa.Numeric(), nullable=False),
    sa.Column('gross_profit', sa.Numeric(), nullable=False),
    sa.Column('gpm', sa.Numeric(), nullable=False),
    sa.Column('sga_expenses', sa.Numeric(), nullable=False),
    sa.Column('rent_expense', sa.Numeric(), nullable=False),
    sa.Column('depreciation_expense', sa.Numeric(), nullable=False),
    sa.Column('amortization_expense', sa.Numeric(), nullable=False),
    sa.Column('bad_debt_expense', sa.Numeric(), nullable=False),
    sa.Column('other_operating_expenses', sa.Numeric(), nullable=False),
    sa.Column('total_operating_expenses', sa.Numeric(), nullable=False),
    sa.Column('total_operating_profit', sa.Numeric(), nullable=False),
    sa.Column('operating_profit_margin', sa.Numeric(), nullable=False),
    sa.Column('interest_expense', sa.Numeric(), nullable=False),
    sa.Column('interest_income', sa.Numeric(), nullable=False),
    sa.Column('other_non_operating_income_expense', sa.Numeric(), nullable=False),
    sa.Column('total_non_operating_income_expense', sa.Numeric(), nullable=False),
    sa.Column('total_profit_before_taxes', sa.Numeric(), nullable=False),
    sa.Column('tax_provision', sa.Numeric(), nullable=False),
    sa.Column('net_income', sa.Numeric(), nullable=False),
    sa.Column('distributions', sa.Numeric(), nullable=False),
    sa.Column('ebida', sa.Numeric(), nullable=False),
    sa.Column('ebitda', sa.Numeric(), nullable=False),
    sa.Column('ebitdar', sa.Numeric(), nullable=False),
    sa.Column('net_profit_margin', sa.Numeric(), nullable=False),
    sa.Column('roa', sa.Numeric(), nullable=False),
    sa.Column('roe', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospect.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('financial')
    op.drop_table('contact')
    op.drop_table('prospect')
    op.drop_table('user')
    op.drop_table('products')
    op.drop_table('clients')
    # ### end Alembic commands ###
